### ISSUE TITLE
Integração com API - CRUD de Lote

### ISSUE THREAD

**Issue by NicholasTavares** [csaifrn/niko-web#78]
- Desenvolver tela de cadastro de lote consumindo a API.
-  Endepoints de referência:
- 1. Cadastro do lote: http://ec2-3-230-86-92.compute-1.amazonaws.com/batches (POST)
- 2. Informações do lote: http://ec2-3-230-86-92.compute-1.amazonaws.com/batches/f58d7b9f-bc1c-4f03-8ebc-9fc3d602e62e (GET)
- 3. Atualizar informações do lote: http://ec2-3-230-86-92.compute-1.amazonaws.com/batches/f58d7b9f-bc1c-4f03-8ebc-9fc3d602e62e (PATCH)
- 4. Deletar lote: http://ec2-3-230-86-92.compute-1.amazonaws.com/batches/f58d7b9f-bc1c-4f03-8ebc-9fc3d602e62e (DELETE)

Observações:
- O usuário deve estar logado e passar o token de acesso (JWT) no header da requisição, exemplo:
`axios.get(API_URL, {
  headers: {
    'Authorization': 'Bearer ' + JWT_TOKEN
  }
})`
No atual ponto de desenvolvimento do projeto, já é realizada a automatização desse processo de passar o token de autenticação no header requisição através do [axiosInstance.ts](https://github.com/csaifrn/niko-web/blob/master/src/api/axiosInstance.ts)
- Nova documentação (POSTMAN): https://interstellar-eclipse-459288.postman.co/workspace/API~84b4d18d-bfb2-4b7e-9fa0-fbf8c24672d9/collection/14496603-81f06268-3349-4551-a30d-b56b142080e7?action=share&creator=14496603

**Comment by NicholasTavares** [comment]
- É previsível que haja mal entendido e diferenças criativas com o design no Figma. Qualquer coisa, fazer anotações para avaliar os requisitos e revisar posteriormente.

**Comment by RafaelaMicaela** [comment]
Incluir notificações quando criar o lote usando a lib https://react-hot-toast.com/
